/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:
Input: s = "", t = "y"
Output: "y"

*/
class FindtheDifference{
	static char findtheDifference(String s,String t){
		int freq[]=new int[26];
		for(char c:s.toCharArray()){
			freq[c-'a']++;
		}

		for(char c:t.toCharArray()){
			if(freq[c-'a']==0){
				return c;
			}
			freq[c-'a']--;
		}
		return ' ';
	}
	public static void main(String[] args) {
		String s = "abcd", t = "abcde";
		System.out.println(findtheDifference(s,t));
	}
}
/*
OUTPUT
e
*/